# Generated by Django 4.1.1 on 2022-10-04 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_dueno', '0001_initial'),
        ('app_ficha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('sexo', models.CharField(max_length=45)),
                ('especie', models.CharField(max_length=45)),
                ('altura', models.CharField(blank=True, max_length=45, null=True)),
                ('color', models.CharField(blank=True, max_length=45, null=True)),
                ('n_microchip', models.CharField(blank=True, max_length=45, null=True)),
                ('raza', models.CharField(blank=True, max_length=45, null=True)),
                ('dueno_id_dueno', models.ForeignKey(db_column='dueno_id_dueno', on_delete=django.db.models.deletion.DO_NOTHING, to='app_dueno.dueno')),
                ('ficha_veterinaria_id_ficha', models.ForeignKey(db_column='ficha_veterinaria_id_ficha', on_delete=django.db.models.deletion.DO_NOTHING, to='app_ficha.fichaveterinaria')),
            ],
            options={
                'db_table': 'animal',
                'managed': True,
            },
        ),
    ]
