# Generated by Django 4.1.1 on 2022-10-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservahoras',
            table='horas',
        ),
    ]
