# Generated by Django 4.1.1 on 2022-10-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserva', '0002_alter_reservahoras_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservahoras',
            table='reserva_horas',
        ),
    ]
