# Generated by Django 4.1.1 on 2022-10-04 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0002_alter_veterinaria_options'),
        ('app_reserva', '0002_alter_reservahoras_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservahoras',
            name='veterinaria_id_veterinaria',
            field=models.ForeignKey(db_column='veterinaria_id_veterinaria', default=6, on_delete=django.db.models.deletion.DO_NOTHING, to='app_veterinaria.veterinaria'),
            preserve_default=False,
        ),
    ]
