# Generated by Django 4.1.1 on 2022-10-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserva', '0003_reservahoras_veterinaria_id_veterinaria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservahoras',
            options={'managed': False},
        ),
    ]
