# Generated by Django 4.1.1 on 2022-10-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_emp', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'emp',
                'managed': False,
            },
        ),
    ]
