# Generated by Django 4.1.1 on 2022-10-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('id_veterinaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vet', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=250)),
                ('especialidad', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('urgencia', models.CharField(blank=True, max_length=45, null=True)),
                ('exoticos', models.CharField(blank=True, max_length=45, null=True)),
                ('odontologia', models.CharField(blank=True, max_length=45, null=True)),
                ('toma_muestras', models.CharField(blank=True, max_length=45, null=True)),
                ('examenes', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'veterinaria',
                'managed': False,
            },
        ),
    ]
