# Generated by Django 4.1.1 on 2022-10-04 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_comuna', '0003_comuna_region_id_region'),
        ('app_veterinaria', '0002_alter_veterinaria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaria',
            name='comuna_id_comuna',
            field=models.ForeignKey(db_column='comuna_id_comuna', default=6, on_delete=django.db.models.deletion.DO_NOTHING, to='app_comuna.comuna'),
            preserve_default=False,
        ),
    ]
