# Generated by Django 4.1.1 on 2022-10-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0003_veterinaria_comuna_id_comuna'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veterinaria',
            options={'managed': False},
        ),
    ]
