# Generated by Django 4.1.1 on 2022-10-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_comuna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'managed': True},
        ),
    ]
