# Generated by Django 4.1.1 on 2022-10-04 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_region', '0002_alter_region_options'),
        ('app_comuna', '0002_alter_comuna_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='region_id_region',
            field=models.ForeignKey(db_column='region_id_region', default=6, on_delete=django.db.models.deletion.DO_NOTHING, to='app_region.region'),
            preserve_default=False,
        ),
    ]
