# Generated by Django 4.1.1 on 2022-10-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_comuna', '0003_comuna_region_id_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'managed': False},
        ),
    ]
