# Generated by Django 4.1.1 on 2022-10-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_procedimiento', '0002_alter_procedimiento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimiento',
            options={'managed': False},
        ),
    ]
