# Generated by Django 4.1.1 on 2022-10-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dueno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dueno',
            options={'managed': True},
        ),
    ]
