# Generated by Django 4.1.1 on 2022-10-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaVeterinaria',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('n_registro', models.IntegerField()),
            ],
            options={
                'db_table': 'ficha_veterinaria',
                'managed': False,
            },
        ),
    ]
