# Generated by Django 4.1.1 on 2022-10-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha', '0002_alter_fichaveterinaria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichaveterinaria',
            options={'managed': False},
        ),
    ]
