# Generated by Django 4.1.1 on 2022-10-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_estado_hora', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadohora',
            options={'managed': True},
        ),
    ]
